name: Github actions

on:
  pull_request:
  push:
    branches:
      - main
      - development
  
jobs:
  build:   
   runs-on: ubuntu-latest
   steps: 
    - uses: actions@v1
    - name: Use Nodejs ${{ matrix.node-version }}
      uses: actions@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm run build --if--present
        npm run start
  
