name: Github actions

on:
  pull_request:
  push:
    branches:
      - main
      - development
  
jobs:
  build:   
   runs-on: ubuntu-latest
   steps: 
    - uses: actions/checkout@v1
    - name: Use Nodejs 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies and Check Quality
      run: |
        npm install
        npm run build --if--present
        npm run test
  
